{{ config (
schema='CURATION_AX_INVENTORY',
  alias='PDSDISPOSITIONMASTER',
  tags=["curation"]
) }}

SELECT
  "DATAAREAID",
  "DESCRIPTION",
  "DISPOSITIONCODE",
  "IBRALLOWPRODUCTION",
  "INVENTLOCATIONID",
  "PARTITION",
  "PDSNETTABLE",
  "PDSPRODBLOCKPICK",
  "PDSPRODBLOCKPRODUCTIONPICKINGJOURNAL",
  "PDSPRODBLOCKRESERVE",
  "PDSSALESBLOCKPICK",
  "PDSSALESBLOCKRESERVE",
  "PDSSALESBLOCKSHIP",
  "PDSTRANSBLOCKPICK",
  "PDSTRANSBLOCKRESERVE",
  "PDSTRANSBLOCKSHIP",
  "RECID",
  "RECVERSION",
  "STATUS",
  "_SDC_BATCHED_AT",
  "_SDC_DELETED_AT",
  "_SDC_EXTRACTED_AT"
FROM "DATAOPS_FB_FEATURERSDEMANDFORECAST_CANDIDATE"."INGESTION_AX"."PDSDISPOSITIONMASTER"
