{{ config (
schema='CURATION_AX_INVENTORY',
  alias='INVENTBATCH',
  tags=["curation"]
) }}

SELECT
  "DATAAREAID",
  "DESCRIPTION",
  "EXPDATE",
  "IBRVENDACCOUNT",
  "INVENTBATCHID",
  "ITEMID",
  "PARTITION",
  "PDSBESTBEFOREDATE",
  "PDSCOUNTRYOFORIGIN1",
  "PDSCOUNTRYOFORIGIN2",
  "PDSDISPOSITIONCODE",
  "PDSFINISHEDGOODSDATETESTED",
  "PDSINHERITBATCHATTRIB",
  "PDSINHERITEDSHELFLIFE",
  "PDSSAMELOT",
  "PDSSHELFADVICEDATE",
  "PDSUSEVENDBATCHDATE",
  "PDSUSEVENDBATCHEXP",
  "PDSVENDBATCHDATE",
  "PDSVENDBATCHID",
  "PDSVENDEXPIRYDATE",
  "PRODDATE",
  "RECID",
  "RECVERSION",
  "_SDC_BATCHED_AT",
  "_SDC_DELETED_AT",
  "_SDC_EXTRACTED_AT"
FROM "DATAOPS_FB_FEATURERSDEMANDFORECAST_CANDIDATE"."INGESTION_AX"."INVENTBATCH"
