{{ config (
schema='CALCULATION_INVENTORY'
  , alias='BATCH'
  , tags=["calculation"]
  , materialized='table'
) }}

SELECT
 B.PARTITION
,B.RECID
FROM {{ ref('CURATION_INVENTBATCH')}}  B
LEFT JOIN {{ ref('CURATION_PDS')}} BD
ON B.PARTITION = BD.PARTITION
AND B.DATAAREAID = BD.DATAAREAID
AND B.PDSDISPOSITIONCODE = BD.DISPOSITIONCODE
